### PR TITLE
Player Initialization Flow and Fix various issues. Fixes #53 and Fixes #68

### LINKED ISSUE #37: Feature: Interpolated Vector3
Currently we only have **MDCRMInterpolatedVector2** which is our Vector2, it would be good to also add an interpolated Vector3. If any functionality is duplicated between the two then it should probably be moved into another class that both the interpolated Vectors can inherit from.

### LINKED ISSUE #53: Player Initialization Flow & Event
When a player first joins a server there's generally some initialization that needs to occur both from the player and from the server. (eg. authenticating with a platform, sending desired user name or character, etc).

To help facilitate this flow, MDPlayerInfo should provide hooks (virtual methods) for users to add this initialization logic and an Event on MDGameSession should be fired to notify once initialization has completed (or failed).

cc @Meister1593

### LINKED ISSUE #68: Rework and document events
Currently events are a bit confusing and poorly document in the framework. In particular it is not clear during which event you should do what, one such example is [this issue](https://github.com/DoubleDeez/MDFramework/issues/7).

The goal of this bug would be to rework events so all important events have pre/post events and clear documentation both in code and on the wiki (with examples on the wiki) for which event should do what. And in particular during which events you should not do certain things to avoid bugs.

Here is a list of things that at a minimum should be done in the scope of this bug,

- All framework events should be documented both in wiki and with the appropriate comment
- Add any events that may be relevant (eg. A new player synch / join event where you can spawn the player. [See this issue.](https://github.com/DoubleDeez/MDFramework/issues/7))
- Ensure events are executed at the correct time (eg. for **OnPlayerLeftEvent** often the MDPlayerInfo is removed before the event, this makes no sense).

### LINKED ISSUE #69: Introduce log override to configuration
Currently if you want to change loglevel for a particular class you have to go in and change this in the file, it would be nice to be able to just do this from the configuration.

There are two things that could be done here,

1. All loglevels for each separate class could be moved into the configuration allowing you to configure the loglevel in config files instead.
2. Introduce a single configuration override setting, which if set would override all other loglevels.

Personally I think at least number 2 would be nice, number 1 might be a bit more of a pain to maintain.

### LINKED ISSUE #82: Resolving of Method for MDRpc should be more accurate
If you look at the following screenshot it has a method,
`SendUpdatePosition(MovementInput, int, float, float)`

issue01

In this screenshot it tries to find the method with the following parameters,
`SendUpdatePosition(MovementInput, uint, float, float)`
issue02

This fails because the second parameter is a _uint_ instead of an _int_. This is not a problem for the basic godot Rpc as it simply casts the _uint_ to an _int_. As such we should rethink how we resolve methods / overloaded methods. Perhaps we should look for the exact one and if not found look for the best match? Or something like this. Or at the very least log an error saying we found these methods with these overloads, but nothing matched your parameters of these types...

### PR DESCRIPTION
**Pull request by DoubleDeez**

### CODE REVIEW

File: MDHelpers/MDConfiguration.cs [hunk 1]
```diff
@@ -143,6 +147,49 @@ public Type GetType(ConfigurationSections Category, string Key, Type Default)
...
+
+        /// <summary>
+        /// Checks if the configuration has set a value for the given category and key
+        /// </summary>
+        /// <param name="Category">The category</param>
+        /// <param name="Key">The key</param>
+        /// <returns>True if the config has a value</returns>
+        public bool HasValue(ConfigurationSections Category, string Key)
+        {
+            return Configuration.HasSectionKey(Category.ToString(), Key);
```
Comment (DoubleDeez) [inline MDHelpers/MDConfiguration.cs:190]: I think this will have to be updated with your config changes

**Comment by DoubleDeez** [comment]
I'll update the example project with the player info changes once this is merged.
This became a bit more than just the player info changes as it was easier to just fix the issues along side the other change.

**Review by Beider — APPROVED** [review]
