### PR TITLE
Fixes for server authoritative setups

### LINKED ISSUE #51: GameSynchronizer ping between peers
In the scope of #49 it is intended to implement the ability to disable server relay. Currently the GameSynchronizer has clients sending ping requests to each other, of course these bounce through the server anyway since there is no P2P communication.

Since these packets go through the server anyway we might as well not have the clients ping eachother. The reason they do ping each other is because we use the highest ping in the game to decide what the _Remote Offset_ should be for the GameClock.

In short the remote offset decides how many game ticks behind remote signals are executed, 1 remote offset is 1 physics frame, ie. roughly 16 milliseconds. So if remote offset is 10 then all remote nodes are running 160 milliseconds behind for that client, this is to ensure we get a smooth behavior from all remote nodes so the data will be there before it is needed. Currently the remote offset is actually adjusted extra high because ping is for an entire roundtrip, half of ping time would be the minimum time you need to get remote signals. In addition we have an additional buffer added on top of the ping (20 % I believe).

So what do we do to solve this in the GameSynchronizer?

```csharp
    private void OnPingTimerTimeout(Timer timer, int PeerId)
    {
        // Check if peer is still active
        if (!InternalPingList.ContainsKey(PeerId) || !MDStatics.IsNetworkActive())
        {
            MDLog.Trace(LOG_CAT, "Peer {0} has disconnected, stopping ping", PeerId);
            timer.Stop();
            timer.RemoveAndFree();
            return;
        }

        // Send ping request
        if (MDStatics.IsClient() || GameClock == null)
        {
            RpcId(PeerId, nameof(RequestPing), OS.GetTicksMsec());
        }
        else
        {
            uint ping = (uint)GetPlayerPing(PeerId);
            uint estimate = GetPlayerTicksMsec(PeerId) + ping;
            RpcId(PeerId, nameof(RequestPing), OS.GetTicksMsec(), estimate, GameClock.GetTickAtTimeOffset(ping));
        }
    }
```

If you look at this method you can see that clients send other peers ping requests, this should be removed (just disable the ping timer for clients and remove the `MDStatics.IsClient()`). Then instead the server should calculate what the "highest ping" should be for each client and send it to the client. The highest ping would be `<clients ping>+<highest ping of remaining peers>`.

Eg.
P1 => Ping : 100
P2 => Ping : 150
P3 => Ping : 200

In this scenario maximum ping would be
P1 => P1 + P3 = 300
P2 => P2 + P3 = 350
P3 => P3 + P2 = 350

This information could be sent along with normal ping packets and then we just need to ensure if you are a client when you are asked for max ping in `GetMaxPlayerPing()` we return this value.

### PR DESCRIPTION
**Pull request by Meister1593**
This fixes #51 and most likely #49

If we disable `server relay`, then client can't make RPC's to eachother. 
Before this PR, each client would ping eachother to calculate remote offsets on their side. Now it's pinging through server. 
There still need for max ping to be not the same for each player (#55), but this is start.

### CODE REVIEW

File: MDGameSynchronizer/MDGameSynchronizer.cs [hunk 1]
```diff
@@ -70,6 +70,7 @@ public class MDGameSynchronizer : Node
         protected int NodeCount = -1;
 
         protected bool NodeSynchCompleted = false;
+        private int MaxPing;
```
Comment (Beider) [inline MDGameSynchronizer/MDGameSynchronizer.cs]: I think like the rest of the variables this should be protected since we allow overwriting the MDGameSynchronizer

File: MDGameSynchronizer/MDGameSynchronizer.cs [hunk 2]
```diff
@@ -524,16 +530,11 @@ private void OnPingTimerTimeout(Timer timer, int PeerId)
...
-            {
-                RpcId(PeerId, nameof(RequestPing), OS.GetTicksMsec());
-            }
-            else
-            {
-                uint ping = (uint) GetPlayerPing(PeerId);
-                uint estimate = GetPlayerTicksMsec(PeerId) + ping;
-                RpcId(PeerId, nameof(RequestPing), OS.GetTicksMsec(), estimate, GameClock.GetTickAtTimeOffset(ping));
-            }
+            uint ping = (uint) GetPlayerPing(PeerId);
```
Comment (Beider) [inline MDGameSynchronizer/MDGameSynchronizer.cs]: The old code was like this,

```csharp
        // Send ping request
        if (MDStatics.IsClient() || GameClock == null)
        {
            RpcId(PeerId, nameof(RequestPing), OS.GetTicksMsec());
        }
        else
        {
            uint ping = (uint)GetPlayerPing(PeerId);
            uint estimate = GetPlayerTicksMsec(PeerId) + ping;
            RpcId(PeerId, nameof(RequestPing), OS.GetTicksMsec(), estimate, GameClock.GetTickAtTimeOffset(ping));
        }
```

This IF still needs to be there for cases where GameClock is not enabled. So please add the IF statement back with the alternative ping method.

**Review by Beider — CHANGES_REQUESTED** [review]
Just two minor fixes to be made. Except for that looks good to me.

**Review by Beider — APPROVED** [review]
