### PR TITLE
Fix multiple crashes that surfaced and removed the naming requirement…

### LINKED ISSUE #42: MDLog should have the ability to log to GD.Print
It should be enabled by default and be able to be disabled.

### PR DESCRIPTION
**Pull request by DoubleDeez**
… for GameInstance autoload

### CODE REVIEW

File: MDNetworking/Misc/MDReplicatorNetworkKeyIdMap.cs [hunk 1]
```diff
@@ -13,8 +14,11 @@ class MDReplicatorNetworkKeyIdMap
 
         public void AddNetworkKeyIdPair(uint id, string key)
         {
-            NetworkIDToKeyMap.Add(id, key);
-            KeyToNetworkIdMap.Add(key, id);
+            if (NetworkIDToKeyMap.ContainsKey(id) == false)
```
Comment (DoubleDeez) [inline MDNetworking/Misc/MDReplicatorNetworkKeyIdMap.cs:17]: I'm not sure if it's expected that the id could be in the map but I was hitting an exception because it existed already (same for the buffer below)

Comment (Beider) [reply MDNetworking/Misc/MDReplicatorNetworkKeyIdMap.cs:17]: That is very weird, It should be impossible for the ID to already be in the map as far as I thought from the way the logic of this works. If the ID exists in the map we have a bigger problem though, just ignoring it with contains won't be good enough I think as this may cause replication to fail. If you are able to reproduce this maybe you can debug it and check if the key for the ID in the list is the same as the one being sent in, because if they are not we got a problem.

Comment (DoubleDeez) [reply MDNetworking/Misc/MDReplicatorNetworkKeyIdMap.cs:17]: Looks like it's the same:
```log
Tried to add key /root/GameSession/@@16#PlayerHealth for id 21 but it already has key /root/GameSession/@@16#PlayerHealth
```
it only happens on the client that joined

**Comment by DoubleDeez** [comment]
Just noticed there's a crash if you disconnect as client and try to start a server so I'm gonna fix that before this should be merged

**Comment by DoubleDeez** [comment]
Looks like it just has to do with all the networking systems not clearing themselves when the session disconnects

**Comment by Beider** [comment]
Alright that seems about right, I thought I cleaned up stuff in OnSessionStart but guess I forgot some stuff. Well I am not surprised there are bugs with all the changes I have made and the very limited tests we got. I will finish up a couple of more issues in the framework then I will start integrating it into my game as well. That should at least help for testing if we got two probjects using it.

File: MDConfigDebug.ini [hunk 2]
```diff
@@ -15,6 +15,7 @@ GameSynchronizerEnabled=true
 UseSceneBuffer=true
 GameClockActive=true
 LogDirectory="user://logs/"
+LogConsoleToGDPrint=true
```
Comment (Beider) [inline MDConfigDebug.ini:18]: You should also add this setting to MDConfigExport.ini, I also noticed that I forgot to copy the latest settings from MDConfigDebug.ini into the export file. So maybe you could just copy all of them in the scope of this PR and set some sensible defaults for exported games.

Comment (DoubleDeez) [reply MDConfigDebug.ini:18]: done

**Review by Beider — APPROVED** [review]
